export default {
    type: 'new_project',
    name: 'Storey McStore Store',
    id: null,
    databaseConnectionType: 'local',
    databaseHost: '127.0.0.1',
    databasePort: '3306',
    databaseUsername: 'root',
    databasePassword: '',
    databases: [],
    databaseType: 'new_database',
    database: '',
    showAdvancedDatabaseOptions: false,
    databaseTestPassed: false,
    elasticsearchConnectionType: 'local',
    elasticsearchVersion: null,
    elasticsearchHost: '127.0.0.1',
    elasticsearchPort: '9200',
    storeIdentifier: null,
    showAdvancedElasticsearchOptions: false,
    elasticsearchTestPassed: false,
    theme: 'Metal',
    storeName: 'Storey McStore Store',
}
